spring.application.name=aula012026

spring.datasource.url=jdbc:postgresql://localhost/aulafull
spring.datasource.username=postgres
spring.datasource.password=123456

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.secretkey: vvg47dg8szer7ghs9v8a7g98ae
spring.emissor: samuelmatos
spring.tempoExpiracao : 30